name: zxing_barcode_scanner_example
description: "Demonstrates how to use the zxing_barcode_scanner plugin."

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  zxing_barcode_scanner:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
