name: zxing_barcode_scanner
description: 'A barcode scanner plugin for Flutter using ZXing-C++ on Android and iOS.'
version: 1.0.1
repository: https://github.com/ShirishAryal/zxing_barcode_scanner

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  pigeon: ^22.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.shirisharyal.zxing_barcode_scanner
        pluginClass: ZxingBarcodeScannerPlugin
      ios:
        pluginClass: ZxingBarcodeScannerPlugin
